global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "user-service"

    static_configs:
      - targets:
          - "user-service:5400"


  - job_name: "product-service"

    static_configs:
      - targets:
          - "product-service:5500"

    
  - job_name: "inventory-service"

    static_configs:
      - targets:
          - "inventory-service:5600"


  - job_name: "order-service"

    static_configs:
      - targets: 
          - "order-service:5700"         


  - job_name: "payment-service"

    static_configs:
      - targets:
          - "payment-service:5800"