apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-service


  template:
    metadata:
      labels:
        app: payment-service
      
    
    spec:
      containers:
      - name: payment-service

        image: akshaya1234/payment-service:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5800

        env:
        - name: DATABASE_URL
          value: postgresql://postgres:akshay1234@postgres:5432/payment_db
